token: token             # Replace with a desired token
os:
  hostname: node1        # Set a hostname. This can be omitted if DHCP server offers hostnames.
  ssh_authorized_keys:
  - ssh-rsa ...          # Replace with your public key
  password: p@ssword     # Replace with a your password
install:
  mode: create
  networks:
    harvester-mgmt:      # The management bond name. This is mandatory.
      bond_option:
        mode: balance-tlb
      interfaces:
      - name: eth0
      method: dhcp
  device: /dev/sda       # The target disk to install
  iso_url: https://releases.rancher.com/harvester/master/harvester-amd64.iso
#  tty: ttyS1,115200n8   # For machines without a VGA console

  vip: 10.10.0.19
  vip_mode: dhcp                   # Or static
  vip_hw_addr: 52:54:00:ec:0e:0b   # Leave empty when vip_mode is static
