---
# Reference:
# https://ranchermanager.docs.rancher.com/pages-for-subheaders/rancher-on-a-single-node-with-docker

- name: Reinstall Rancher
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Check rancher is enabled
      assert:
        that: rancher_config.enabled

    - name: Check network
      shell: virsh -c qemu:///system net-info harvester
      register: shell_result
      failed_when: shell_result.rc != 0

    - name: remove Rancher
      shell: vagrant destroy -f rancher && sleep 10

    - name: install Rancher {{ rancher_config.version }}
      shell: vagrant up rancher

    - name: wait for Rancher {{ rancher_config.hostname }} to get ready
      uri:
        url: "https://{{ rancher_config.hostname }}"
        validate_certs: no
        status_code: 200
        force: true
      register: http_resp
      until: http_resp.status == 200
      retries: 10
      delay: 30
