---
- name: Setup Harvester
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - debug:
      msg: Installation Started

  - name: install PXE server
    shell: >
      vagrant up pxe_server
    register: pxe_server_installation_result

  - name: get the IP address of pxe_server
    shell: |
      vagrant ssh-config pxe_server 2>/dev/null | grep HostName | awk '{ print $2 }'
    register: get_pxe_server_ip_result
    until: get_pxe_server_ip_result != ""
    retries: 10
    delay: 60

  - name: set pxe_server_ip fact
    set_fact:
      pxe_server_ip: "{{ get_pxe_server_ip_result.stdout }}"

  - name: wait for PXE server HTTP port to get ready
    uri:
      url: "http://{{ pxe_server_ip }}/harvester/config-create.yaml"
      status_code: 200
    register: pxe_server_http_result
    until: pxe_server_http_result.status == 200
    retries: 10
    delay: 30

  - name: boot Harvester nodes
    include_tasks: boot_harvester_node.yml
    vars:
      node_number: "{{ item }}"
    with_sequence: 0-{{ harvester_network_config['cluster'] | length - 1 }}

  - name: install Rancher {{ rancher_config.version }}
    shell: >
      vagrant up rancher
    when: rancher_config.enabled

  - name: wait for Rancher {{ rancher_config.hostname }} to get ready
    uri:
      url: "https://{{ rancher_config.hostname }}"
      validate_certs: no
      status_code: 200
      force: true
    register: http_resp
    until: http_resp.status == 200
    retries: 10
    delay: 30
    when: rancher_config.enabled

  - debug:
      msg: Installation Completed

